apiVersion: v1
kind: Pod
metadata:
  name: mysqlbd
  namespace: aulainfra
  labels:
    app: mysqlbd
spec:
  containers:
    - name: mysqlbd
      image: mysql
      ports:
        - containerPort: 3306